// =============================================================================
// Groth16 Proof Verifier for zkBridge Light Client
// =============================================================================
// Verifies Groth16/BN254 proofs generated by snarkjs/rapidsnark from the
// circom split-circuit pipeline (8 parts: part1a..part3b).
//
// Usage:
//   cargo run --release -- <build_directory>              # Verify all 8 parts
//   cargo run --release -- <build_directory> part1a part2  # Verify specific parts
//
// Each part directory must contain: proof.json, public.json, vkey.json
// =============================================================================

use std::env;
use std::fs;
use std::path::Path;
use std::str::FromStr;
use std::time::Instant;

use ark_bn254::{Bn254, Fq, Fq2, Fr, G1Affine, G2Affine};
use ark_groth16::{Groth16, Proof, VerifyingKey};
use ark_snark::SNARK;
use serde_json::Value;

const PARTS: &[&str] = &[
    "part1a", "part1b", "part1c", "part1d", "part1e", "part2", "part3a", "part3b",
];

// =============================================================================
// JSON -> arkworks parsers
// =============================================================================

/// Parse a JSON value (string or number) into a BN254 base field element (Fq).
fn parse_fq(val: &Value) -> Fq {
    let s = match val {
        Value::String(s) => s.clone(),
        Value::Number(n) => n.to_string(),
        _ => panic!("Expected string or number for Fq, got: {}", val),
    };
    Fq::from_str(&s).unwrap_or_else(|_| panic!("Invalid Fq value: {}", s))
}

/// Parse a JSON value (string or number) into a BN254 scalar field element (Fr).
fn parse_fr(val: &Value) -> Fr {
    let s = match val {
        Value::String(s) => s.clone(),
        Value::Number(n) => n.to_string(),
        _ => panic!("Expected string or number for Fr, got: {}", val),
    };
    Fr::from_str(&s).unwrap_or_else(|_| panic!("Invalid Fr value: {}", s))
}

/// Parse a JSON array [c0, c1] into Fq2 = c0 + c1*u.
fn parse_fq2(val: &Value) -> Fq2 {
    let arr = val.as_array().expect("Expected array for Fq2");
    Fq2::new(parse_fq(&arr[0]), parse_fq(&arr[1]))
}

/// Parse a snarkjs G1 point [x, y, "1"] into G1Affine.
fn parse_g1(val: &Value) -> G1Affine {
    let arr = val.as_array().expect("Expected array for G1 point");
    G1Affine::new_unchecked(parse_fq(&arr[0]), parse_fq(&arr[1]))
}

/// Parse a snarkjs G2 point [[x0,x1], [y0,y1], ["1","0"]] into G2Affine.
fn parse_g2(val: &Value) -> G2Affine {
    let arr = val.as_array().expect("Expected array for G2 point");
    G2Affine::new_unchecked(parse_fq2(&arr[0]), parse_fq2(&arr[1]))
}

// =============================================================================
// File loaders
// =============================================================================

fn load_proof(path: &Path) -> Proof<Bn254> {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
    let data: Value = serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("Invalid JSON in {}: {}", path.display(), e));

    Proof {
        a: parse_g1(&data["pi_a"]),
        b: parse_g2(&data["pi_b"]),
        c: parse_g1(&data["pi_c"]),
    }
}

fn load_public_inputs(path: &Path) -> Vec<Fr> {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
    let data: Value = serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("Invalid JSON in {}: {}", path.display(), e));

    data.as_array()
        .expect("public.json must be a JSON array")
        .iter()
        .map(parse_fr)
        .collect()
}

fn load_verification_key(path: &Path) -> VerifyingKey<Bn254> {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
    let data: Value = serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("Invalid JSON in {}: {}", path.display(), e));

    let ic: Vec<G1Affine> = data["IC"]
        .as_array()
        .expect("vkey.json must contain IC array")
        .iter()
        .map(parse_g1)
        .collect();

    VerifyingKey {
        alpha_g1: parse_g1(&data["vk_alpha_1"]),
        beta_g2: parse_g2(&data["vk_beta_2"]),
        gamma_g2: parse_g2(&data["vk_gamma_2"]),
        delta_g2: parse_g2(&data["vk_delta_2"]),
        gamma_abc_g1: ic,
    }
}

// =============================================================================
// Verification logic
// =============================================================================

struct VerifyResult {
    part: String,
    valid: bool,
    num_public_inputs: usize,
    num_ic: usize,
    load_time_ms: u128,
    verify_time_ms: u128,
    error: Option<String>,
}

fn verify_part(build_dir: &Path, part: &str) -> VerifyResult {
    let part_dir = build_dir.join(part);
    let proof_path = part_dir.join("proof.json");
    let public_path = part_dir.join("public.json");
    let vkey_path = part_dir.join("vkey.json");

    // Check files exist
    for (name, path) in [
        ("proof.json", &proof_path),
        ("public.json", &public_path),
        ("vkey.json", &vkey_path),
    ] {
        if !path.exists() {
            return VerifyResult {
                part: part.to_string(),
                valid: false,
                num_public_inputs: 0,
                num_ic: 0,
                load_time_ms: 0,
                verify_time_ms: 0,
                error: Some(format!("{} not found in {}", name, part_dir.display())),
            };
        }
    }

    // Load artifacts
    let load_start = Instant::now();
    let proof = load_proof(&proof_path);
    let public_inputs = load_public_inputs(&public_path);
    let vk = load_verification_key(&vkey_path);
    let load_time_ms = load_start.elapsed().as_millis();

    let num_public_inputs = public_inputs.len();
    let num_ic = vk.gamma_abc_g1.len();

    // Verify: IC must have exactly nPublic + 1 entries
    if num_ic != num_public_inputs + 1 {
        return VerifyResult {
            part: part.to_string(),
            valid: false,
            num_public_inputs,
            num_ic,
            load_time_ms,
            verify_time_ms: 0,
            error: Some(format!(
                "IC length mismatch: IC has {} entries but {} public inputs (expected {})",
                num_ic,
                num_public_inputs,
                num_ic - 1
            )),
        };
    }

    // Verify using Groth16 SNARK trait
    let verify_start = Instant::now();
    match Groth16::<Bn254>::verify(&vk, &public_inputs, &proof) {
        Ok(valid) => {
            let verify_time_ms = verify_start.elapsed().as_millis();
            VerifyResult {
                part: part.to_string(),
                valid,
                num_public_inputs,
                num_ic,
                load_time_ms,
                verify_time_ms,
                error: if valid {
                    None
                } else {
                    Some("Proof verification failed (pairing check)".to_string())
                },
            }
        }
        Err(e) => {
            let verify_time_ms = verify_start.elapsed().as_millis();
            VerifyResult {
                part: part.to_string(),
                valid: false,
                num_public_inputs,
                num_ic,
                load_time_ms,
                verify_time_ms,
                error: Some(format!("Verification error: {}", e)),
            }
        }
    }
}

// =============================================================================
// Main
// =============================================================================

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: {} <build_directory> [part1a part1b ... | all]", args[0]);
        eprintln!();
        eprintln!("Examples:");
        eprintln!("  {} ./build_128_one              # Verify all 8 parts", args[0]);
        eprintln!("  {} ./build_128_one part1a part2  # Verify specific parts", args[0]);
        eprintln!();
        eprintln!("Available parts: {}", PARTS.join(", "));
        std::process::exit(1);
    }

    let build_dir = Path::new(&args[1]);
    if !build_dir.is_dir() {
        eprintln!("Error: '{}' is not a directory", build_dir.display());
        std::process::exit(1);
    }

    let parts_to_verify: Vec<&str> = if args.len() > 2 {
        args[2..].iter().map(|s| s.as_str()).collect()
    } else {
        PARTS.to_vec()
    };

    println!();
    println!("  Groth16 Proof Verifier (BN254) - zkBridge Light Client");
    println!("  ======================================================");
    println!();
    println!("  Build dir:  {}", build_dir.display());
    println!("  Parts:      {:?}", parts_to_verify);
    println!();

    let total_start = Instant::now();
    let mut results: Vec<VerifyResult> = Vec::new();

    for part in &parts_to_verify {
        print!("  [{:6}] ", part);

        let result = verify_part(build_dir, part);

        if let Some(ref err) = result.error {
            if result.num_public_inputs == 0 && result.load_time_ms == 0 {
                println!("SKIP  - {}", err);
            } else {
                println!(
                    "FAIL  - {} (load: {}ms, verify: {}ms, {} public inputs)",
                    err, result.load_time_ms, result.verify_time_ms, result.num_public_inputs
                );
            }
        } else {
            println!(
                "OK    - valid proof (load: {}ms, verify: {}ms, {} public inputs)",
                result.load_time_ms, result.verify_time_ms, result.num_public_inputs
            );
        }

        results.push(result);
    }

    let total_elapsed = total_start.elapsed();

    // Summary
    let ok_count = results.iter().filter(|r| r.valid).count();
    let fail_count = results.iter().filter(|r| !r.valid && r.error.is_some() && r.num_ic > 0).count();
    let skip_count = results.iter().filter(|r| !r.valid && r.num_ic == 0).count();

    println!();
    println!("  ------------------------------------------------------");
    println!(
        "  Results:    {} valid, {} invalid, {} skipped",
        ok_count, fail_count, skip_count
    );
    println!("  Total time: {:.2?}", total_elapsed);
    println!("  ------------------------------------------------------");
    println!();

    if fail_count > 0 {
        std::process::exit(1);
    }
}
